### ISSUE TITLE
element should not be changed before click edit icon - and click edit icon can change elements, slider should change value too

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#1]
![image](https://cloud.githubusercontent.com/assets/8002065/26553503/1fe1ddc4-44b6-11e7-9520-4955b031f85e.png)

**Comment by sonit1810** [comment]
1. Please show slider as "grey line" with green circle (and the rest of right is white so it look like grey line from left has length = big of value ) ?

make reps max 10
time max = 10 mins
sets max 5
rest max 10
also make side circle just green dot, when not active/edit
if possible

2. When click edit active, it will show slider as current design

**Comment by sonit1810** [comment]
3. when click edit  icon, it allows to edit, and edit icon -> save icon, click save will save values of that params and reshow panel params too, it works better

**Comment by divppc** [comment]
please check on this page current issue about slider and issue #2 about active class for chosen exercise, i'll upload it if everything ok http://physio.div.agency/program-builder-tools.html

**Comment by sonit1810** [comment]
Hi,

Slider disabled and enabled when clicked, it's great. Can you make icon save so i can switch to it when click edit ? So edit <--> save icons switch when clicked ?

![image](https://cloud.githubusercontent.com/assets/8002065/26563758/67c85cee-4501-11e7-895b-8ef0c713ee60.png)

**Comment by sonit1810** [comment]
Value not changed when i change slider (drag slider )

**Comment by divppc** [comment]
change values - ok, but we don't have save icon in this project, can i toggle pencil icon and 'Save' word? or should find save icon

**Comment by sonit1810** [comment]
I discussed with Justin. Actually no need pencil now. Just show slider with correct value, and when adjust silder it will auto save. So you can leave it & hide pencil now.

**Comment by divppc** [comment]
leave slider always available for changing and remove overlay?

**Comment by sonit1810** [comment]
Yes, actually sliders will show when i click to exercise item in the list,
else it will hide. So you can remove overlay and leave them active, i can
control, but i need slider works (value will changed when drag).

**Comment by divppc** [comment]
ok, please check slider http://physio.div.agency/program-builder-tools.html

**Comment by sonit1810** [comment]
okay, work great. Can you add place holder for function handle drag release
( i drag slider to new positon/value, and release mouse, then this function
will called/triggered )

Thanks!

**Comment by divppc** [comment]
i left you comment http://joxi.ru/MAjG5l3C4a8eyr

**Comment by sonit1810** [comment]
Great, thank you!
