### ISSUE TITLE
Need click to title of frequency it becomes to dropdown list 

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#11]
**# This is minimum priority**

Currently when add program, we can select frequency

![image](https://cloud.githubusercontent.com/assets/8002065/26591335/8918727c-4587-11e7-94f8-cc29034ac095.png)

At program builder page, can we click & make that fields editable ?

![image](https://cloud.githubusercontent.com/assets/8002065/26591406/bd2ff83c-4587-11e7-861b-a7d6e8e00dd1.png)

**Comment by divppc** [comment]
done
