### ISSUE TITLE
Active exercise (Justin, upwork)

### ISSUE THREAD

**Issue by divppc** [divppc/Physio-App#13]
and when click exercise, need to show as active, to edit correct slider (slider relates to exercise), and also exercise title which is under media preview box, should be the active one

---------------------

only one should be able to be active at once, can we make active outline green?

---------------------

when exercise active, slider should relate to that active exercise, and title under preview should be same as active exercise

**Comment by divppc** [comment]
done partially.
now we can select only one exercise, and it's name will be insert into preview name
http://joxi.ru/D2P4nQKIpalpb2

but as i understood from Justin message - each exercise should have own program settings slider. I think you can you duplicate them yourself later.

**Comment by sonit1810** [comment]
I told Justin name of exercise can be replaced by active exercise , but i
will do it when select exercise and set it active
