### ISSUE TITLE
List Item alignment wrong in modal popup

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#14]
If i put tag a between images/video in your sample code, item in list look very funny. But i need put link to photo so it can open in another window to view fully size.

![image](https://cloud.githubusercontent.com/assets/8002065/26609016/e697fca6-45c8-11e7-9fbe-4360c51a80d5.png)

![image](https://cloud.githubusercontent.com/assets/8002065/26609028/f4b851be-45c8-11e7-9e0f-69773929cc28.png)

**Comment by divppc** [comment]
if you need put link there, then play icon can't be link also, that's why you see this effect

a {
		    display: block;
		    width: 75px;
		    height: 65px;
		    margin: 0 auto;
		    position: absolute;
		    top: 50%;
		    left: 50%;
		    background: url(assets/images/icons.png) no-repeat 0px -285px;
		    -webkit-transform: translate(-50%, -50%);
		    -ms-transform: translate(-50%, -50%);
		    transform: translate(-50%, -50%);
			}

**Comment by sonit1810** [comment]
Can you add css for that block so it can has link and list does not broken ?

You can check online at here

http://mpa.jsoft.com.au/application/dashboard/programBuilding#

Select "Justin test 1", click exercise, then preview icon to show popup, you will see

![image](https://cloud.githubusercontent.com/assets/8002065/26610785/fdf8c8f2-45d3-11e7-889a-4b2516c501fd.png)

**Comment by divppc** [comment]
you should put img inside a for video btn 
http://joxi.ru/nAyB18nSY345or

**Comment by divppc** [comment]
done

**Comment by sonit1810** [comment]
Worked. Thanks.
