### ISSUE TITLE
Need Forgot password link for login form

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#15]
I think best position is right side of Login button, with a nice padding ?

![image](https://cloud.githubusercontent.com/assets/8002065/26722839/04d40d14-47bc-11e7-8af4-a62a9336c34d.png)

**Comment by divppc** [comment]
if you want forgot link right side from login button, that need to do some changes in structure.
Need wrap login button in div, and put forgot link via position: absolute

 If put forgot link below login button, that need only style this link. so it's easier. Please decide

**Comment by sonit1810** [comment]
Then please put it below login button. thanks!

**Comment by divppc** [comment]
done http://physio.div.agency/login.html
