### ISSUE TITLE
Reduce size of images

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#16]
Some images have big size, so it slows downloading, and client already feedback.

Example this one

http://mpa.jsoft.com.au/assets/images/tristan-colangelo.png

Can you reduce images size , using some tool, example this https://tinypng.com/

It can compress png file to less size without lost quality, can you try ?

Thanks!

**Comment by divppc** [comment]
ok. i'll do it

**Comment by divppc** [comment]
done http://joxi.ru/D2P4nQKIpaypv2

**Comment by sonit1810** [comment]
thanks
