### ISSUE TITLE
Need elements become to textbox/editable when click Edit on General setting page

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#18]
Do you know Angular Ihor ? May it can help implement quicker ?

![image](https://cloud.githubusercontent.com/assets/8002065/26775939/528260aa-4a01-11e7-85bd-20858206912a.png)

**Comment by divppc** [comment]
i don't work with angular, But i think this can be done as inputs with disabled attribute

**Comment by divppc** [comment]
please see solution about editing details in first section, if this ok, i'll do same for second section with working hours

http://physio.div.agency/general-settings.html

**Comment by sonit1810** [comment]
Great, it's good.

For working hours, i think we need make it select hours from(AM) to (PM), not sure if it match client expected, but let do that way first.

**Comment by divppc** [comment]
done http://physio.div.agency/general-settings.html

**Comment by sonit1810** [comment]
Need make textarea for address, and select list for timezone

![image](https://user-images.githubusercontent.com/8002065/26886350-4ac22330-4bcf-11e7-924e-5e849003238c.png)

**Comment by divppc** [comment]
done

**Comment by sonit1810** [comment]
Great, please commit changes.
