### ISSUE TITLE
Need active class for item in list exercise of program selected (maybe has border)

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#2]
![image](https://cloud.githubusercontent.com/assets/8002065/26553579/7349c620-44b6-11e7-8418-9f38ff74e322.png)

**Comment by divppc** [comment]
now it's a link, can i remove <a> tag from here?

**Comment by sonit1810** [comment]
I don't know what type using, but we should make item clicked active (has border?), and we should keep drag & delete icons as is too, i will try implement drag function,

**Comment by divppc** [comment]
ok, i'll add active class for it

**Comment by divppc** [comment]
done
