### ISSUE TITLE
back button on add new program page needs to be new button design style

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#20]
![image](https://cloud.githubusercontent.com/assets/8002065/26779659/7179f40a-4a10-11e7-8b96-2cd89b69c25b.png)

**Comment by divppc** [comment]
like this? http://joxi.ru/D2P4nQKIpanBn2

**Comment by sonit1810** [comment]
Yes maybe, i don't understand exactly what client meant. Actually Justin talk with him. So just do it. 

Thanks.

**Comment by divppc** [comment]
done http://physio.div.agency/create-program.html
