### ISSUE TITLE
Stars are rating of client engagement overall so should sit in column 1

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#21]
![image](https://cloud.githubusercontent.com/assets/8002065/26780518/52459aa4-4a14-11e7-9df1-88bf65d27563.png)

**Comment by divppc** [comment]
move rating stars under div.current-status? http://joxi.ru/L21vBb9u8LlgXA

**Comment by divppc** [comment]
moved, but now there are some changes in structure, please refresh it in your app
http://physio.div.agency/program-builder-tools.html
