### ISSUE TITLE
Remove buttons of video player

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#22]
*** Video is downloadable from this lightbox- again not cool as it is giving away one of our key advantages.
No sound or download or fullscreen icon required. Please remove.
Could not exit the light box - no button, clicking off the box didn’t work, had to refresh or exit browser.

--> Can you remove "sound", "download", "fullscreen" buttons of that iframe video player ?

![image](https://cloud.githubusercontent.com/assets/8002065/26780836/c91a3a58-4a15-11e7-8b84-010c65e1291b.png)

**Comment by divppc** [comment]
please provide me a link to this page. If you insert video via external iframe - it can't be changed. But if you use html5 video tag, that you can set settings for player.

**Comment by sonit1810** [comment]
Ca you create simple html5 video tag witj hide buttons? Then i can apply. Or you can check at here

mpa.jsoft.com.au/application/dashboard/programBuilding

**Comment by divppc** [comment]
just remove attribute "controls" from video tag http://joxi.ru/ZrJNKyQS96KvOr

**Comment by divppc** [comment]
no, wait

**Comment by divppc** [comment]
If you delete this attribute, the video will not work. The only option is to enable auto-play, but in this case, the pause will not be available...

This is a standard html5 tag and it is displayed differently in all browsers. We can not delete a specific button from the player, only all together.

**Comment by sonit1810** [comment]
So we can not remove "fullscreen", "sound" and "download" buttons ? this will be big problem. I will let Justin now

**Comment by sonit1810** [comment]
Can you try use another video player such as JW Player ?

**Comment by divppc** [comment]
installed new player (not commited yet) please see http://joxi.ru/BA0MYv9fJ45eDr

on this page http://physio.div.agency/program-builder-tools.html click on video button and then click on 3rd media item. You want to delete some buttons?
