### ISSUE TITLE
Need mobile, tag for profile view column on program builder page

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#23]
![image](https://cloud.githubusercontent.com/assets/8002065/26815321/ee2600ac-4ab5-11e7-8f69-5ea9231d9224.png)

**Comment by divppc** [comment]
I'm not sure I understand you. Just add two links?

Add mobile
Add tag

?

**Comment by sonit1810** [comment]
Yes just add them, i will control when they display

**Comment by divppc** [comment]
added http://physio.div.agency/program-builder-tools.html

**Comment by sonit1810** [comment]
Can you move Add mobile below email ? because if client has mobile then it will display below email, for tags we can leave it at there because there maybe have many tags, we need wide area to display tags

![image](https://user-images.githubusercontent.com/8002065/26871674-31b595ba-4b9e-11e7-923c-568c3b135a36.png)

**Comment by divppc** [comment]
done
