### ISSUE TITLE
Add save button for general setting page

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#24]
We need "save" button at bottom of each form/section. Please add button, no need write script show/hide button, i will do it.

![image](https://user-images.githubusercontent.com/8002065/26934460-a5f1e776-4c93-11e7-9b1d-96ea3908d909.png)

**Comment by divppc** [comment]
ok, and wrap all fields in form tag? or not necessary

**Comment by sonit1810** [comment]
No i think we just need add button Save so we can press it to save, now
when you click Edit, this button becomes to Save (use same button for
Edit/Save), now we split to 2 button Edit and Save , press Edit will make
input editable, and show Save button.  press save will save, disable
inputs, and show edit button. I will write js to show/hide buttons.

**Comment by divppc** [comment]
done. commited

**Comment by sonit1810** [comment]
Can you align edit  & save button ?

![image](https://user-images.githubusercontent.com/8002065/26943289-412c03f0-4caf-11e7-9c79-acf1af2d4afc.png)

**Comment by divppc** [comment]
aligned, commited
