### ISSUE TITLE
Add Save & Delete button for notes

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#25]
Can you format notes as textarea, and add button for save & delete it ?

![image](https://user-images.githubusercontent.com/8002065/26934806-9c8cbdcc-4c94-11e7-9578-8e9e8c66ee1e.png)

**Comment by divppc** [comment]
ok

**Comment by divppc** [comment]
done http://physio.div.agency/program-builder-tools.html

**Comment by sonit1810** [comment]
Can you make Delete button same style with others ? Maybe just gray color
and red when hover ? I'm not sure because it does not exist in design, this
is Justin new request

**Comment by divppc** [comment]
maybe add eventListener for Delete button and remove note?

**Comment by sonit1810** [comment]
No i meant you make button "delete " style like remove program button
style, red background when hover ? just make they are same style and look
nice.

**Comment by divppc** [comment]
not understand what's wrong, they identical http://joxi.ru/E2pVZgzh9YKQwr

**Comment by sonit1810** [comment]
Ok, i saw it, it's ok, i'm checking  style at dev site.

**Comment by sonit1810** [comment]
Also, please use class for css later for element, you used id now it's hard for me :D since i used that id in js code too

![image](https://user-images.githubusercontent.com/8002065/26943476-f1328ec2-4caf-11e7-8fd1-241ff7fdc996.png)


![image](https://user-images.githubusercontent.com/8002065/26943493-fbc14afe-4caf-11e7-8447-e38f13634fd6.png)

**Comment by divppc** [comment]
changed, commited
