### ISSUE TITLE
Please create a form for adding exercise

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#26]
Please create form for adding exercise, basically we need section for name, other  params (like resp, set...we saw in program builder page) , and section for upload media files (image, video...), we will use jquery upload plugin (demo at https://blueimp.github.io/jQuery-File-Upload/index.html ).

Just do html/css layout, i will add that jquery upload plugin later, but if you can add & style button match site style then it would be great.

Thanks!

![add-exercise](https://user-images.githubusercontent.com/8002065/27224177-e985ace0-52bd-11e7-9449-a334cf11e642.png)

**Comment by divppc** [comment]
here page http://physio.div.agency/add-exercise.html

try to insert plugin in div.file-uploads and then i'll style all buttons http://joxi.ru/82QDX5Zfj6NYPm

**Comment by divppc** [comment]
commited

**Comment by sonit1810** [comment]
Hi Ihor,

Please move it to right side as image below

You can try at here

http://mpa.jsoft.com.au/application/setting/add-exercise

It used bootstrap to load icon, you can define new style and we can remove bootstrap css ? I removed out of bootstrap css so you see icons are flat,  they look nice at here https://blueimp.github.io/jQuery-File-Upload/



![need](https://user-images.githubusercontent.com/8002065/27328468-72502a7a-55dc-11e7-914f-84f3fc652765.png)

**Comment by divppc** [comment]
Hi Son. 

Ok, I'll do it tomorrow,  you can remove bootstrap.

**Comment by divppc** [comment]
there are mistake, please move .file-uploads in form tag http://joxi.ru/8AnGlVxCjX3vGr

like in my page http://joxi.ru/Rmzeyk9h0QBbor

then this block will be on the right side

**Comment by sonit1810** [comment]
No Ihor, they are different form, 2 form, left form and right form. Because uploader uses ajax, we can not put them into one form, so please fix css :dancing_men: 

Thanks!

**Comment by sonit1810** [comment]
Also, can you add 2 select for Type & Part ?

Also, after move that section to right side, can you add overlay for that section, so if we press Save in left section then it will remove overlay of right section ? The idea is only can upload media file if exercise saved(added) first.

Thanks!

![image](https://user-images.githubusercontent.com/8002065/27424043-ef92418a-575d-11e7-8c4f-818dcad22da0.png)

**Comment by divppc** [comment]
Hi Son, understood, ok.

But i need working link to see the existing structure and style it.
http://mpa.jsoft.com.au/application/setting/add-exercise - not work

http://joxi.ru/EA49YvQswj3kzr

**Comment by sonit1810** [comment]
I can open it normal

Can you open http://mpa.jsoft.com.au ?

Else can you add this line into host file ? it will work. I think your computer has DNS problem

50.28.18.17 mpa.jsoft.com.au

![image](https://user-images.githubusercontent.com/8002065/27431865-2ebb0116-5778-11e7-806c-7e58de0778aa.png)

**Comment by sonit1810** [comment]
Or you can access bitbucket repo

https://bitbucket.org/mpa-bitbucket/mpa-api

https://bitbucket.org/mpa-bitbucket/mpa-api/src/964f61fc062095106f8201fed0a87f52c6565668/module/Application/view/application/setting/add-exercise.phtml?at=master&fileviewer=file-view-default

**Comment by divppc** [comment]
please try to add my ip to whitelist 93.77.143.234
i don't have permission to your repo

**Comment by sonit1810** [comment]
server already turn off firewal

Your image show your DNS server had problem when access mpa.jsoft.com, not from server firewall. Can you restart your modem/router ?

**Comment by divppc** [comment]
please see this page http://physio.div.agency/add-exercise.html

**Comment by sonit1810** [comment]
Hi Ihor,

Which js call will remove overlay of upload form section ?

**Comment by divppc** [comment]
Hi Son.

http://joxi.ru/eAOlO1LIxQ0wLr

**Comment by sonit1810** [comment]
Thanks Ihor,

Can you add css styles for buttons in right secion ?

http://mpa.jsoft.com.au/application/setting/add-exercise

Maybe made upload buttons look like this : https://blueimp.github.io/jQuery-File-Upload/

**Comment by divppc** [comment]
Yes, i can style buttons with these sizes and colors, but there are used font for icons, So if you want icons too, then i'll find pictures for it.

**Comment by divppc** [comment]
here buttons http://physio.div.agency/add-exercise.html
just update styles

**Comment by sonit1810** [comment]
Hi Ihor,

http://mpa.jsoft.com.au/application/setting/add-exercise

Please style for missing buttons . To see "Start" "Cancel" button in list, please "Add Files" and choose some pictures on your computer.

Also, where there are "overlay" removed with latest update ? Or i added missing something on the form ?

![image](https://user-images.githubusercontent.com/8002065/27526812-6c15ded0-5a72-11e7-9d57-26b5d24f7eb4.png)

**Comment by sonit1810** [comment]
Do you see style at this page ? Please try add some files

https://blueimp.github.io/jQuery-File-Upload/

- each line of file list has different color for odd/even row
- each file has small progress bar
- it has big one progress bar a buttons line at top too
- it has color for uploading progress bar, and upload success 

Can you make button class as global, not for specified page add exercise ? since i maybe use them for other pages.

![image](https://user-images.githubusercontent.com/8002065/27528480-baaacddc-5a7a-11e7-848a-a9d7de633b85.png)


![image](https://user-images.githubusercontent.com/8002065/27528448-965a0bc8-5a7a-11e7-9a2f-fd06182a4c21.png)


![image](https://user-images.githubusercontent.com/8002065/27528401-6f7756dc-5a7a-11e7-9f6e-1029dfddb100.png)

**Comment by sonit1810** [comment]
Hi Ihor,

Please try choose Big file size to upload and you will see progress bar, we need style it the same style with sample url 

![image](https://user-images.githubusercontent.com/8002065/27582574-8835f570-5b5b-11e7-866a-5dedb9c714e4.png)

**Comment by divppc** [comment]
Hi Son. 

Ok, I'll work on it today

**Comment by divppc** [comment]
Hi Son.

Please update styles from this repo and i'll test changes about file upload form. I added styles for progress bar, and odd table rows. Also button's classes are public now. And returned overlay.

Thanks

**Comment by sonit1810** [comment]
Please check, text, buttons not show now, :dancing_men: 

http://mpa.jsoft.com.au/application/setting/add-exercise

Please try choose Add files and choose some files, you will see upload button & cancel button, existing file will have delete button.

![image](https://user-images.githubusercontent.com/8002065/27730037-1a2570a2-5db2-11e7-8b7c-afe8a3d7efff.png)


![image](https://user-images.githubusercontent.com/8002065/27730038-1cb10174-5db2-11e7-9521-ec84e5d279ea.png)

**Comment by divppc** [comment]
Hi Son.

Please update styles
