### ISSUE TITLE
FIRST PRIORITY - Please change team member page , add list of rows

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#34]
Hi Ihor, THIS IS FIRST PRIORITY, PLEASE DO THIS ASAP, Justin will create new project for you.

Justin wants restructure team member page like this

So in each row, it has columns 
username, email, role , action,

in role, it has 4 radio buttons with style you made in team-member form.

In top right, it has Edit like other section. And bottom right make Save button too (like you did in general setting page)

Click to Edit, will switch to edit mode for this list. If in edit mode list, click to each cell in table will make cell editable. Name & Email & Role can editable.

Just do click cell make it editable, i will do js to check in edit mode.

![image](https://user-images.githubusercontent.com/8002065/28052669-8538669c-6636-11e7-9beb-4425e82b42ee.png)

**Comment by sonit1810** [comment]
For button [Add], it should popup team member form (as current form), but i will do that for you, i know how to popup the form.

Thanks!

**Comment by divppc** [comment]
Hi Son. This table should be here http://physio.div.agency/general-settings.html below existing content or here http://physio.div.agency/team-members.html, instead invite form.

**Comment by sonit1810** [comment]
Sorry Ihor, please change in team member page, does not change in setting page, sorry.

**Comment by divppc** [comment]
you need header on this page? http://physio.div.agency/team-members.html

**Comment by divppc** [comment]
done

**Comment by divppc** [comment]
invite form commented on this page
