### ISSUE TITLE
Need Send Invite in dashboard

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#35]
Hi Ihor,

1. Can you add button "Invite" next to profile in middle column

2. Can you add textbox & "send invite" button in same row, in 3rd column ?

Thanks!

![image](https://user-images.githubusercontent.com/8002065/28056229-5753149c-6646-11e7-9ed5-4aad76c73f98.png)

**Comment by divppc** [comment]
Hi Son. About third column. Should i delete existing content now? http://joxi.ru/p27OY7WIopKnM2

**Comment by sonit1810** [comment]
Yes Ihor,

Maybe you comment out of that sections and add new one.

**Comment by sonit1810** [comment]
Hi Ihor,

Please get these design for Invite email

https://zpl.io/Z2jBHBo
https://zpl.io/rRK5R

Thanks!

**Comment by sonit1810** [comment]
Hi Ihor can you do this asap, this is urgent

Thanks!

**Comment by divppc** [comment]
done, commited http://physio.div.agency/invite.html

but resend icon is broken http://joxi.ru/bmokKVxTx0k16m
cant download and use it. Please contact designer about it

**Comment by sonit1810** [comment]
Please get new file at here

https://zpl.io/28LX9X

Thanks!

**Comment by divppc** [comment]
you need new page Add mobile? http://joxi.ru/5md09MdFkndZ0m

and there also missed resend icon

**Comment by sonit1810** [comment]
Add Mobile just need popup as i told on another issue. 

Does this new design file contains add mobile screen ? I could not open it, i just send link to you.

**Comment by sonit1810** [comment]
Hi Ihor,

Please add "add mobile" and "add tag" follow that design

**Comment by divppc** [comment]
done
http://physio.div.agency/program-builder-tools.html
