### ISSUE TITLE
Please add style white background for disabled select list

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#36]
Hi Ihor,

Please login to mpa.jsoft.com.au
triton
12345 (or 123456)

Then go to setting

http://mpa.jsoft.com.au/application/setting

You will see select list disabled look bad, please style it, it's select2() select list disabled.

Thanks!

![image](https://user-images.githubusercontent.com/8002065/28112555-9b0bcebc-6723-11e7-8cdb-677abb9dbd93.png)

**Comment by divppc** [comment]
done, please try to update styles

**Comment by sonit1810** [comment]
Thanks Ihor. I added class myself. But let me try your new style.
