### ISSUE TITLE
Please style add member form

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#38]
Hi Ihor, 

I show form as popup, but it looks silly, can you style it ? Also, overlay does not affect to bottom ?

Thanks!

![image](https://user-images.githubusercontent.com/8002065/28244107-6073b180-6a0b-11e7-8638-4e118bfe9343.png)

**Comment by sonit1810** [comment]
Sorry i forgot, please login at here

http://mpa.jsoft.com.au/

triton@gmail.com
12345

**Comment by divppc** [comment]
fixed, try to update styles
