### ISSUE TITLE
Need plus icon add article like icon add exercise 

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#4]
![image](https://cloud.githubusercontent.com/assets/8002065/26564922/d2c923b6-4510-11e7-9d32-600ab362463d.png)
![image](https://cloud.githubusercontent.com/assets/8002065/26564931/e64b121e-4510-11e7-8c35-5d274fe859b1.png)

**Comment by divppc** [comment]
now + icon it's pseudo element :after
you need this icon as separate tag or it can be done via :after for articles too?

**Comment by sonit1810** [comment]
That (+) icon should show like it show in exercise list for exercise item.

**Comment by divppc** [comment]
done http://physio.div.agency/program-builder-tools.html

**Comment by sonit1810** [comment]
Verified.
