### ISSUE TITLE
Remove border of textbox on emails box of dashboard

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#41]
Hi Ihor,

Please login to 

http://mpa.jsoft.com.au/application/dashboard

triton@gmail.com
12345

I changed textbox to multiple values of select2, which can allow user type tags into the select list, and it works. Now i need you remove border of textbox when typing. Can you make css like this

.users-form .style...{
}

I just want it apply to Dashboard page only. (invite.html).  I can add wrapper class, and you add style to affect to textbox of select2 to that class container only

![image](https://user-images.githubusercontent.com/8002065/28615964-222a1d84-7225-11e7-8e13-0f603b3ddf42.png)

Thanks!

![image](https://user-images.githubusercontent.com/8002065/28615860-c300f5ee-7224-11e7-99d2-7570f475bca1.png)

**Comment by divppc** [comment]
done, please try to update styles
