### ISSUE TITLE
Need reload icon for resend-invite class on invite page

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#42]
I added text "Invite sent - Resend" with icon of class "send-invite" on invite page.

Now Justin need that icon use reload icon, you can get it at here https://loading.io/

So please add class "resend-invite" with that reload icon, so i can use it, thanks!

![image](https://user-images.githubusercontent.com/8002065/28618968-9753e71a-7230-11e7-95fd-60b231e6186e.png)

![image](https://user-images.githubusercontent.com/8002065/28619003-baa965dc-7230-11e7-93ce-46cda5546c9b.png)

**Comment by divppc** [comment]
done, here example http://physio.div.agency/invite.html
