### ISSUE TITLE
Please add like for [x] day on program builder

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#43]
Hi,

Please  add like for [x] days , with [x] is drop down , in same line, (maybe need move PAIN SCALE to right a bit).

![image](https://user-images.githubusercontent.com/8002065/28873618-a2f2d8dc-77b8-11e7-8d70-9b9cf66a734b.png)

**Comment by divppc** [comment]
done http://joxi.ru/Dr8vYEdu4YLM12

**Comment by sonit1810** [comment]
hi Ihor,

Please add after "for x days". Start date [textbox when click]

Thanks!

**Comment by divppc** [comment]
please check http://physio.div.agency/program-builder-tools.html

there are no enough free space on small desktops

**Comment by sonit1810** [comment]
Ok let leave it like that Ihor, we will fix for small desktop later

**Comment by divppc** [comment]
done

**Comment by sonit1810** [comment]
Hi Ihor,

please make spacing between each the same, they look overlap now

![image](https://user-images.githubusercontent.com/8002065/28992417-2d7cd0da-79c5-11e7-8585-db200183c4de.png)

**Comment by divppc** [comment]
There is the same indent between all elements. But the width of each element select depends on its maximum value. Therefore visually different indentation
