### ISSUE TITLE
Need global class for chat message data so i can use for dialog

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#45]
Hi Ihor,

I copied the chat form you made for chat page, to popup dialog, and it lost style, i need its style like the one you made on chat box, i think you should made global class for that form so i can use , please do this asap.

Thanks!

![image](https://user-images.githubusercontent.com/8002065/29005558-e2783518-7b07-11e7-99b6-566808015040.png)

![image](https://user-images.githubusercontent.com/8002065/29005563-eee1e614-7b07-11e7-8cc5-627b148e84af.png)

![image](https://user-images.githubusercontent.com/8002065/29005567-fe2a07b4-7b07-11e7-965e-605698649a4f.png)

**Comment by divppc** [comment]
about what form you talking? please show original page, not understood

**Comment by sonit1810** [comment]
Hi Ihor,

Please login to https://mpa.jsoft.com.au/
triton@gmail.com
12345

Then go to Chat page, in chat list, click PRIVATE REPLY, it will popup dialog, i cloned that form elements but all elements broken, i need their style look like the one you enter message text to send in main window

Thanks!

**Comment by divppc** [comment]
understand, thanks. Now, new message field is global form
