### ISSUE TITLE
Style of upload buttons changed in latest css

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#49]
Hi Ihor,

Some how Add files button becomes to bigger, and row has 'white' area

We have upload section in My Exercises -> Add exercise and Articles -> add article

![image](https://user-images.githubusercontent.com/8002065/29016820-415a0c7a-7b7e-11e7-9e7b-61746cad3fd4.png)

**Comment by divppc** [comment]
Hi Sonit, please provide link, where i can see and check this problem. Thanks

user triton and password 123456 not correct now

**Comment by sonit1810** [comment]
Hi Ihor

Please use triton@gmail.com , password 12345

**Comment by divppc** [comment]
done

**Comment by divppc** [comment]
You updated styles and upload button still looks bad?

**Comment by divppc** [comment]
please update styles and everything will be ok
