### ISSUE TITLE
Profile page

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#50]
Hi Ihor,

Please cut profile page, it's urgent

Thanks

https://zpl.io/29DDEyb

**Comment by divppc** [comment]
You talk about this page? https://yadi.sk/i/Z5VUIKv93LnMi8

because you sent link to home page

**Comment by sonit1810** [comment]
Hmm, Justin sent me that link. If he sent you correct link then it's ok.

**Comment by divppc** [comment]
He did not send me anything, I found this new page in the project. Please see screenshot https://yadi.sk/i/Z5VUIKv93LnMi8

**Comment by divppc** [comment]
done

**Comment by sonit1810** [comment]
Hi Ihor,

This is Justin said

"it has icon for linking from search home page.
there should also be the profile settings page."

So i think the page you found corrected

**Comment by sonit1810** [comment]
Hi Ihor,

Can you show me which icon linked to profile page, from home page (dashboard page) ? I can not access that project files so i can not see anything

Thanks!

**Comment by divppc** [comment]
Hi Son.

I think Justin said about this icon https://yadi.sk/i/jDHf0Y7o3Lpk8j

it's new icon in project

**Comment by sonit1810** [comment]
Hi Ihor,

Then please add that icon into home2.html or index.html

Thanks!

**Comment by divppc** [comment]
done http://physio.div.agency/home2.html

**Comment by sonit1810** [comment]
Too bad, profile icon look very silly among with other icons, let me ask Justin

![image](https://user-images.githubusercontent.com/8002065/29181826-c802b95c-7e26-11e7-9a65-311f492cc9b3.png)

**Comment by divppc** [comment]
Yes, i agree, but this icon from layout. I don't understand why designer used another size

**Comment by sonit1810** [comment]
Hi Ihor, please remove circle, text..just keep icon , it would work

"that looks silly in that image because of the profile word, and the cicle around the icon, and because it is out of alignment. remove profile label, remove circle, and make same alignment. and it will look good."

We need place that profile icon on left slide bar on program building page too, so please make it.

Thanks!

**Comment by divppc** [comment]
done http://physio.div.agency/home2.html

**Comment by sonit1810** [comment]
hi Ihor,

The first phone octet length is 3, now it's 2. Can you fix this ?

![image](https://user-images.githubusercontent.com/8002065/29682557-a1925bdc-8935-11e7-86bd-57414b90dd42.png)

**Comment by divppc** [comment]
fixed, now 3 symbols, try here http://physio.div.agency/personal-profile.html
