### ISSUE TITLE
Need reponsive for popup/lightbox

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#53]
Hi Ihor, this is what client said

"light boxes aren't formatted for responsive screen in vertical dimension. Result is where there are light boxes on my 13inch screen I can't see the cancel button at the bottom. Creates a roadblock that I can't exit from. Occurs in video play, new program light box and I assume anywhere else we have them. Simple is to use smaller light boxes."

Can we make a popup sample with responsive (just add class or style responsive for current popup ?) so i can apply for other ?

Thanks!

**Comment by divppc** [comment]
done, now height of modal body depends from screen height

**Comment by sonit1810** [comment]
hi Ihor,

I think you made something wrong, slider stretched now ?

![image](https://user-images.githubusercontent.com/8002065/29181530-b6b18bd4-7e25-11e7-87f3-745f9d5b5c6c.png)

**Comment by divppc** [comment]
Hi Sonit, i just show you example that you can manage slider items in html file via data attributes, now returned back.
