### ISSUE TITLE
Need max-height for chat window

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#55]
I think we need set max-height for chat window. It need scroll if chat is too long

![image](https://user-images.githubusercontent.com/8002065/29245627-583b6ed0-800a-11e7-99cd-10d12f7896e7.png)

**Comment by divppc** [comment]
done http://physio.div.agency/chat_v2.html

**Comment by sonit1810** [comment]
I think you misunderstood, haha,

The message box form should stay at bottom, while message area should have scroll if too long

![image](https://user-images.githubusercontent.com/8002065/29548096-63db832c-8728-11e7-987d-ddf929749fec.png)

**Comment by divppc** [comment]
done http://physio.div.agency/chat_v2.html
