### ISSUE TITLE
Profile icon need grey & green when hover

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#56]
Now it always green, can you fix it ?

![image](https://user-images.githubusercontent.com/8002065/29510064-bc31a91a-8684-11e7-9131-3b434e6a8a22.png)

**Comment by divppc** [comment]
Hi Sonit. Ok, I'll fix it today. But must to say that I'm on vacation from tomorrow until 02.09

**Comment by divppc** [comment]
done

**Comment by sonit1810** [comment]
The icon seem bigger a big when hover , can you check on mpa.jsoft.com.au ?

**Comment by sonit1810** [comment]
Can you make it lighter when hover ? Now it's too bold

![image](https://user-images.githubusercontent.com/8002065/29647004-f937c406-88b0-11e7-9593-36337cc0dc55.png)

**Comment by divppc** [comment]
this icon from designer is too bold, can i use another similar icon from internet?

**Comment by sonit1810** [comment]
Hi Ihor,

You should use that icon. Can you reduce bold for it ?

**Comment by divppc** [comment]
Can't make it thinner, need to contact designer about it, or i'll use something like this
https://www.google.com.ua/search?q=user+icon+png&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwjdusSL-I7WAhXoHpoKHSZPAfsQsAQIJg&biw=1920&bih=974#imgrc=Plgxs1fCqwDyKM:

**Comment by sonit1810** [comment]
Yes Ihor, you can use that icon. Actually you can choose which one you
think is best, you'r designer so you can make it look good as you think,
haa.

Thanks!

**Comment by divppc** [comment]
Icon changed http://physio.div.agency/home2.html
