### ISSUE TITLE
Program builder page - types & parts buttons

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#62]
Hi Ihor,

This is what Justin say

1. make a "Parts" drop down, when drop down should reveal the filter boxes.
2. make "Type" drop down, make box buttons instead of drop down menu.

Can you clone current program-tool-page1 and make new one with Parts and Type as drop down ?

Thanks!

**Comment by divppc** [comment]
Hi Sonit. Not sure that understand you, please show on screenshot. Thanks
http://physio.div.agency/program-builder-tools.html

**Comment by sonit1810** [comment]
Ok Ihor,

1. parts and types filtering... need to change to use only buttons

--> It means you need make part to buttons too.


See this one : https://www.diigo.com/item/image/5vg4r/bvr3

in the screenshot... #1 is the type section. we want the type section to
start off looking like #2 section. then when you click to expand the
section it looks like #1.
same with #2 section. when you click to expand, we want it to look like #1.

He wants make collapse/close for Types and Part sections

Collapse/open icon can get from another design files which i will send to
you

**Comment by divppc** [comment]
if i understood correctly, you need one button for types section and "+ icon". When click plus - all another buttons shows and plus button changes to "-" button for collapsing.

Parts section same - only one button visible and "+" icon shows.

Right?

**Comment by sonit1810** [comment]
1. Currently part is select dropdown , type are  buttons. We need make part are buttons too

2. Add - to expand Type & Part sections, and + to collapse. Default load is collapsed. 

Make sense?

**Comment by divppc** [comment]
After page loading, two sections are hidden and we see only two "+" icons? These sections don't have any title, so it's would not be understandable for users which sections are hidden, agree?

**Comment by sonit1810** [comment]
Yes, hmm, can you use (-) and (+) icons as for title ?Temporary like that,
we need update on front-end to show for client, and we can adjust it later.

**Comment by divppc** [comment]
Hi Sonit.

Please check buttons for Parts and Types on this page http://physio.div.agency/program-builder-tools.html

if everything ok - i'll upload it
