### ISSUE TITLE
Urgent task design changes

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#64]
Please check these design changes, this is urgent, thanks!

https://zpl.io/bz8YpP8
https://zpl.io/adxAnv5

**Comment by divppc** [comment]
you need also all of this links with new icons? http://joxi.ru/xAeJo0LSpqXGwr

**Comment by divppc** [comment]
on this page http://physio.div.agency/program-builder-tools.html

right sidebar also should be collapsible and positioned by absolute? now it fixed here, but in new design they overlaps content from right side, on this page it should be positioned by absolute value http://joxi.ru/EA49YvQswypVDr

**Comment by divppc** [comment]
or only on this page right side bar should overlaps the content from right side? and stay fixed here http://physio.div.agency/program-builder-tools.html

**Comment by sonit1810** [comment]
Hi Ihor,

For this one : https://zpl.io/bz8YpP8 
Yes i think this page contains new icon only, can you change to use that icons ?

For this one : https://zpl.io/adxAnv5
I don't know why put a panel in right side like that, that panel does not have any meaning on Insight page. Let me ask Justin

**Comment by sonit1810** [comment]
I think he want right bar can collapse at this page http://physio.div.agency/program-builder-tools.html

And keep Insight page stayed, no add right bar to Insight page. Please do it ASAP Ihor

**Comment by divppc** [comment]
Please check this page http://physio.div.agency/active-programs.html

tell me please if something wrong or if something else must be changed.
This page not uploaded yet, awaiting for your feedback.

**Comment by sonit1810** [comment]
Sorry i don't know because i don't design page, and Justin just ask designer do it, and give file to me to ask you cut/update. It's very hard for me to understand it. So now i don't understand. So please keep Insight page as now, don't do any changes on it.

**Comment by sonit1810** [comment]
Insight page = active-programs.html, don't do any change until i get confirm from Justin, because new design file look very silly if we add right bar , no meaning.

**Comment by divppc** [comment]
ok, i'll be waiting instructions from you

**Comment by sonit1810** [comment]
Ok, please wait for Insight page

And do changes for Program Builder Page, add Collapse for Right Bar, with design like this one

![image](https://user-images.githubusercontent.com/8002065/30442798-b97abb22-99a7-11e7-8537-4710038f2ba5.png)

**Comment by divppc** [comment]
sure about this? now on Program builder page right sidebar has usual static position, if i'll change it to position: absolute and collapse sidebar - page will looks like this http://joxi.ru/xAeJo0LSpqbY1r

everything in the center content will be wider

**Comment by sonit1810** [comment]
Yes i think that's what Justin want, add collapse to right bar. Please do
it.

**Comment by sonit1810** [comment]
Also don't forget remain small line/icon on the right when right bar
collapsed so we can expand it again.

Please do Part to buttons as Type section, and add collapse & expand option
to Type & Part section, as i requested in another issue too.

Thanks!

**Comment by divppc** [comment]
done, uploaded, awaiting for review
