### ISSUE TITLE
Need scroll for second column in search page

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#66]
Hi Ihor,

Please login to mpa.jsoft.com.au, and type "t" , in second column you will see it returns list and overlap, can you add scroll for that div ? I think it's simple css ?

Thanks!

![image](https://user-images.githubusercontent.com/8002065/30424592-9c2516ee-9970-11e7-88b0-41648d2eaa83.png)

**Comment by divppc** [comment]
done
