### ISSUE TITLE
Team member page

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#69]
Hi Ihor,

Please cut this team member page (new design)

https://zpl.io/2j5Nopb

Thanks!

**Comment by sonit1810** [comment]
Pleas notes left sidebar has new icons for pages too, please use that new icons.

Thanks!

**Comment by sonit1810** [comment]
![image](https://user-images.githubusercontent.com/8002065/30518755-8bc3f6b6-9bb0-11e7-9102-2daddbedd07b.png)

**Comment by divppc** [comment]
missing icons http://joxi.ru/p27OY7WIoYg0V2

**Comment by sonit1810** [comment]
Hi IHor,

Designed reup file https://zpl.io/2j5Nopb

Thanks!

**Comment by divppc** [comment]
Hi Sonit, please check the link, it doesn't work for me

**Comment by sonit1810** [comment]
Hi Ihor,

Justin said he can access it, can you retry ?

**Comment by divppc** [comment]
now it works, thanks

**Comment by divppc** [comment]
Hi Sonit.

Please ask designer to provide pencil icon too, he missed it.
Thanks

**Comment by divppc** [comment]
Sonit, i'm almost finished new team page, should i wait for missing pencil from designer or find something similar in the internet?

**Comment by sonit1810** [comment]
Hi Ihor,

Please find one icon similar to use. 

Thanks.

**Comment by sonit1810** [comment]
Hi Ihor,

Also new mockup uploaded at https://zpl.io/2j5Nopb

Meaning of icons

![image](https://user-images.githubusercontent.com/8002065/30736572-7c582610-9fad-11e7-8bbc-84f13936ba0e.png)

**Comment by divppc** [comment]
done http://physio.div.agency/team.html

**Comment by sonit1810** [comment]
so the file member-new.html is empty ?

![image](https://user-images.githubusercontent.com/8002065/30841838-769f8986-a2a8-11e7-9a44-8196b78ced7c.png)

**Comment by divppc** [comment]
here link 

> done http://physio.div.agency/team.html

member-new.html can be deleted

**Comment by sonit1810** [comment]
ok Ihor,
I used that layout for other setting pages and it works fine.

Can you add profile icon for left side bar, from profile icon on dashboard ?

![image](https://user-images.githubusercontent.com/8002065/30851533-15a5e758-a2d3-11e7-82b6-c62bafa1be15.png)


![image](https://user-images.githubusercontent.com/8002065/30851566-2c040bba-a2d3-11e7-8fb6-952d45c267c5.png)

**Comment by divppc** [comment]
Hi Sonit, yes, ok

**Comment by sonit1810** [comment]
Hi Ihor,

ID for color of type of Role,  does it affect to other effect ? I followed your format, then it works. But when i changed name of select list to different then it does not work. 

![image](https://user-images.githubusercontent.com/8002065/30852228-46f270ea-a2d5-11e7-948d-409ff2390b5a.png)

**Comment by divppc** [comment]
please provide link for this page

**Comment by sonit1810** [comment]
Don't worry Ihor, i understand how it works now, thanks

![image](https://user-images.githubusercontent.com/8002065/30852731-f5cce1a8-a2d6-11e7-8742-53021fa12afa.png)

**Comment by divppc** [comment]
Yes, it's take role from selected option)

**Comment by sonit1810** [comment]
Also, I saw you used label:after to make effect of radio button ROLE, but if one row has status active (value=1) then i don't know how to set it to green ? Can you add class so if value = 1 i can set it for radio or label so it can checked (green color)?

![image](https://user-images.githubusercontent.com/8002065/30854757-d6294854-a2dc-11e7-8776-2669dec5b65e.png)

**Comment by sonit1810** [comment]
Sorry Ihor, my bad, i can set radio checked, and it display ok now.
Thanks & sorry, i'm mad now.

**Comment by divppc** [comment]
It's a usual input[type="checkbox"] you can change status by attribute checked http://joxi.ru/v294YlLI3w6vxm

i hope this helps you

**Comment by divppc** [comment]
ok, no problem)

**Comment by sonit1810** [comment]
Hi Ihor,

It does not affect if it's checked, then i set it inactive, it does not remove checked attribute of checkbox , so data submit is wrong

![image](https://user-images.githubusercontent.com/8002065/30855422-3309c56a-a2df-11e7-89fb-62ff7f8c1e98.png)

**Comment by sonit1810** [comment]
![image](https://user-images.githubusercontent.com/8002065/30855472-5d1b5f58-a2df-11e7-8886-ec04287421a1.png)

**Comment by divppc** [comment]
Input type checkbox don't have inactive attribute, it can only be checked or remove attribute checked. And in HTML5 you don't need to write checked="checked", only one word checked is enough. Please see screen shot http://joxi.ru/v294YlLI3w6vxm

**Comment by sonit1810** [comment]
You can try : http://mpa.jsoft.com.au/application/setting/team-members

try change row "Lead Physio Test" (click Pencil icon to edit that row), change status to Inactive, and save it, and reload page, you will see it display active again.

And after you change to inactive, check html code, the radio still has checked="checked", that's why data submit active=1

**Comment by sonit1810** [comment]
yes, i now, can use checked or checked="checked" no matter, what i meant is when you click to radio to set it inactive (not checked), color of button changed to gray and it moved to left, look correct on UI, but in HTML , that radio still checked, that's caused data submit wrong when saving

![image](https://user-images.githubusercontent.com/8002065/30855698-05f15056-a2e0-11e7-87ed-255b3d60919d.png)

**Comment by divppc** [comment]
it works fine for me http://joxi.ru/Q2KVZ75h4EjxKm

i change row, turn off activity, save changes, reload pages and everything saved

**Comment by sonit1810** [comment]
No Ihor, what you saw is in UI, actually data posted wrong, the radio does not changed checked to unchecked , compare UI by these steps
- first load
- change ui, see UI , and data posted
- reload, and see UI again, it's the same at first load, radio does not changed 

I'm using Chrome in Windows Version 60.0.3112.113

Please see this video

https://www.youtube.com/watch?v=9E4zY-C9rJQ&feature=youtu.be

**Comment by sonit1810** [comment]
It works now Ihor, don't worry, it's a bug in coding, my god, i'm mad nowwww

**Comment by divppc** [comment]
yes, everything ok with input, you did something wrong when try to get input value 
here video https://drive.google.com/file/d/0B0_xf8lTXfWBTXE0RkRGNm9pR0U/view?usp=sharing

**Comment by divppc** [comment]
> I used that layout for other setting pages and it works fine.

> Can you add profile icon for left side bar, from profile icon on dashboard ?


done http://physio.div.agency/team.html

**Comment by sonit1810** [comment]
Hi Ihor,

I added hyperlink for columns, it has different color

![image](https://user-images.githubusercontent.com/8002065/31051935-9062e75e-a6a0-11e7-831f-886308bedcf3.png)


![image](https://user-images.githubusercontent.com/8002065/31051937-9a74e80a-a6a0-11e7-804e-0587858d1f85.png)

And when i click to one column, i set class for it, and it changed position too 

![image](https://user-images.githubusercontent.com/8002065/31051941-ba343a2e-a6a0-11e7-95f1-3d8ce26bc48b.png)

Can you check and fix it ? Columns position and color should keep as first load, when click to column.

**Comment by divppc** [comment]
Hi Sonit, fixed

**Comment by sonit1810** [comment]
Thanks!
