### ISSUE TITLE
Can not click arrow down to drop down select list

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#7]
Some points could not clicked.

Justin notes we need all bug fixed tonight so we can show for client on tomorrow morning. Thanks

![image](https://cloud.githubusercontent.com/assets/8002065/26585448/51953eea-4576-11e7-817a-1a583ba2cf7a.png)

![image](https://cloud.githubusercontent.com/assets/8002065/26585453/58a32b98-4576-11e7-995f-f85c8f678331.png)

**Comment by divppc** [comment]
done

**Comment by sonit1810** [comment]
Verified. Good.
