### ISSUE TITLE
Edits on general settings page 

### ISSUE THREAD

**Issue by divppc** [divppc/Physio-App#74]
> i also need to add room on the general settings page for the company website url... https://www.diigo.com/item/image/5vg4r/g45r... i would also like to make all pages where we edit, to make the icons blue when they edit mode is active, and green when the edit mode is inactive... also remove "edit" word... shown on screenshot... thanks!

**Comment by divppc** [comment]
done, except upload image button - it always available http://physio.div.agency/general-settings.html

**Comment by sonit1810** [comment]
I have control by js to make sure it's disabled until press edit icon.,
don't worry Ihor. Actually i think you just add website url, that's enough,
lol
