### ISSUE TITLE
Dashboard, add client wrong style

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#76]
Hi Ihor,

Please login to mpa.jsoft.com.au, and check add client form, it has style very strange now , please fix it

![image](https://user-images.githubusercontent.com/8002065/31078570-de455710-a7ac-11e7-9be5-8089ca9242f7.png)

**Comment by divppc** [comment]
find this in style.css

.home .add-users input[type="email"]

and remove [type="email"]
