### ISSUE TITLE
Need drag item in list

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#8]
You can see demo at here

http://jqueryui.com/sortable/#connect-lists

Can you try apply to list ? I just need item can drag around in that list, i can handle update order number on background by ajax

![image](https://cloud.githubusercontent.com/assets/8002065/26586493/83004ad0-4579-11e7-99aa-d0dfc40463a5.png)

**Comment by divppc** [comment]
ok, i'll try. Never did this before

**Comment by sonit1810** [comment]
^^, you can do it
More article, but i think jquery ui document is enough
http://www.elated.com/articles/drag-and-drop-with-jquery-your-essential-guide/

**Comment by divppc** [comment]
done)
http://physio.div.agency/program-builder-tools.html

**Comment by sonit1810** [comment]
I don't know where the number index show in top left corner of item ? is it auto ?

![image](https://cloud.githubusercontent.com/assets/8002065/26587507/c207c264-457c-11e7-9647-c466bae7915b.png)

it has 8 item total, but when i drag item 4 to 8 position, it becomes show 9, you can try

![image](https://cloud.githubusercontent.com/assets/8002065/26587612/fee3ad74-457c-11e7-9791-b5fb01e3bf31.png)

when i drag item to right, it return back without change position, you can try

![image](https://cloud.githubusercontent.com/assets/8002065/26587682/350c81dc-457d-11e7-85ab-8ed250467f27.png)

**Comment by divppc** [comment]
indexes are added automatically before list items by this rule:

&:before {
		content: counter(item);
  		counter-increment: item;
  		display: block;
  		width: 22px;
  		height: 22px;
  		position: absolute;
  		top: 0;
  		background: #fff;
  		left: 0;
  		border: solid 1px rgb(230, 235, 241);
  		border-radius: 3px;
  		font-size: 12px;
		font-weight: bold;
		letter-spacing: -0.1px;
		color: rgb(107, 124, 147);
		text-align: center;
		line-height: 23px;
	}

**Comment by sonit1810** [comment]
Ok then you can leave it now, we can improve it later, actually maybe we
remove number, it's better.
