### ISSUE TITLE
Need popup dialog for click to video/media place holder

### ISSUE THREAD

**Issue by sonit1810** [divppc/Physio-App#9]
We need a popup dialog with save/close button. i will use this popup for media list, and video play, create program form...

![image](https://cloud.githubusercontent.com/assets/8002065/26588473/a58135be-457f-11e7-8740-1df95a3ff16d.png)

It should work like before, i will make ajax call & fill content...just make popup dialog with sample list, it's ok.

![show_video](https://cloud.githubusercontent.com/assets/8002065/26588484/acf6ce08-457f-11e7-9ab3-3e8fd205c91a.png)
![media_list](https://cloud.githubusercontent.com/assets/8002065/26588485/ad233524-457f-11e7-90f7-adbe7997621f.png)

**Comment by divppc** [comment]
please give link, where i can get popup

**Comment by sonit1810** [comment]
You should define popup dialog yourself, i captured from old version and
show you, you should make popup dialog with style match new design.

I'm using git & implementing using new design, i switched to old version to
see, and now i switched back to new version already.

**Comment by divppc** [comment]
one popup for media list with play buttons for each, and one popup for video, right?

**Comment by sonit1810** [comment]
yes, one popup with media list, if photo then show photo thumb item, if
video then show video icon. and one for video popup, click to video icon
will popup video dialog, you can use temp video url , i will replace it
with correct one later.

**Comment by divppc** [comment]
done
